title: "E-Parking System"
remote_theme: cepdnaclk/eYY-project-theme
description: "An autonomous system for assigning and managing parking spots and payments in a car park."

theme: jekyll-theme-slate
